### ISSUE TITLE
ReferenceError: window is not defined - 0.1.12

### ISSUE THREAD

**Issue by chunkiat82** [bcbcarl/react-c3js#10]
2] [dev:server] 
[2] [dev:server] .../node_modules/c3/c3.js:8202
[2] })(window);
[2]    ^
[2] [dev:server] ReferenceError: `window is not defined`
[2]     at Object.<anonymous> (.../node_modules/c3/c3.js:8202:4)
[2]     at Module._compile (module.js:541:32)
[2]     at Object.Module._extensions..js (module.js:550:10)
[2]     at Module.load (module.js:458:32)
[2]     at tryModuleLoad (module.js:417:12)
[2]     at Function.Module._load (module.js:409:3)
[2]     at Module.require (module.js:468:17)
[2]     at require (internal/module.js:20:19)
[2]     at Object.<anonymous> (.../node_modules/react-c3js/react-c3js.js:15:10)
[2]     at Module._compile (module.js:541:32)

no issues when reverted to 0.1.8

**Comment by bcbcarl** [comment]
@chunkiat82: Can you give me an example and reproduce steps?

**Comment by bcbcarl** [comment]
You can reopen this issue when needed.
