### ISSUE TITLE
Component cannot be rendered on the server side

### ISSUE THREAD

**Issue by maZahaca** [bcbcarl/react-c3js#13]
Hey,
I've added this component to the page and it fails while page is trying to render on the server side.

I'm getting error: 
/front-page/node_modules/c3/c3.js:8202
})(window);
   ^
ReferenceError: window is not defined
    at Object.<anonymous> (/front-page/node_modules/c3/c3.js:8202:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/front-page/node_modules/react-c3js/react-c3js.js:15:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)

**Comment by maZahaca** [comment]
Hey, when we can expect release of this issue?

**Comment by bcbcarl** [comment]
@maZahaca: `v0.1.15` released.

https://github.com/bcbcarl/react-c3js/releases/tag/v0.1.15
